config/routes.rb
Projeto02::Application.routes.draw do
  get "test/start"

  resources :systems

  resources :rules

  resources :conclusions

  resources :premises

  resources :values

  resources :variables

  root :to => 'test#start'

  
  match 'variables/:variable_id/values' => 'values#variables_values'
  
  match 'test/start/:system_id' => 'test#start_test'
end

app/models/conclusion.rb
class Conclusion < ActiveRecord::Base
  attr_accessible :description, :rule_id
end

app/controllers/conclusions_controller.rb
class ConclusionsController < ApplicationController
  # GET /conclusions
  # GET /conclusions.json
  def index
    @conclusions = Conclusion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conclusions }
    end
  end

  # GET /conclusions/1
  # GET /conclusions/1.json
  def show
    @conclusion = Conclusion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @conclusion }
    end
  end

  # GET /conclusions/new
  # GET /conclusions/new.json
  def new
    @conclusion = Conclusion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @conclusion }
    end
  end

  # GET /conclusions/1/edit
  def edit
    @conclusion = Conclusion.find(params[:id])
  end

  # POST /conclusions
  # POST /conclusions.json
  def create
    @conclusion = Conclusion.new(params[:conclusion])

    respond_to do |format|
      if @conclusion.save
        format.html { redirect_to Rule.find(@conclusion.rule_id), notice: 'Conclusion was successfully created.' }
        format.json { render json: @conclusion, status: :created, location: @conclusion }
      else
        format.html { render action: "new" }
        format.json { render json: @conclusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /conclusions/1
  # PUT /conclusions/1.json
  def update
    @conclusion = Conclusion.find(params[:id])

    respond_to do |format|
      if @conclusion.update_attributes(params[:conclusion])
        format.html { redirect_to @conclusion, notice: 'Conclusion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @conclusion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conclusions/1
  # DELETE /conclusions/1.json
  def destroy
    @conclusion = Conclusion.find(params[:id])
    @conclusion.destroy

    respond_to do |format|
      format.html { redirect_to conclusions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/conclusions_helper.rb
module ConclusionsHelper
end

app/views/conclusions/_form.html.erb
<%= form_for(@conclusion) do |f| %>
  <% if @conclusion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conclusion.errors.count, "error") %> prohibited this conclusion from being saved:</h2>

      <ul>
      <% @conclusion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conclusions/edit.html.erb
<h1>Editing conclusion</h1>

<%= render 'form' %>

<%= link_to 'Show', @conclusion %> |
<%= link_to 'Back', conclusions_path %>

app/views/conclusions/index.html.erb
<h1>Listing conclusions</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @conclusions.each do |conclusion| %>
  <tr>
    <td><%= conclusion.description %></td>
    <td><%= link_to 'Show', conclusion %></td>
    <td><%= link_to 'Edit', edit_conclusion_path(conclusion) %></td>
    <td><%= link_to 'Destroy', conclusion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Conclusion', new_conclusion_path %>

app/views/conclusions/new.html.erb
<h1>New conclusion</h1>

<%= render 'form' %>

<%= link_to 'Back', conclusions_path %>

app/views/conclusions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @conclusion.description %>
</p>


<%= link_to 'Edit', edit_conclusion_path(@conclusion) %> |
<%= link_to 'Back', conclusions_path %>