config/routes.rb
Projeto02::Application.routes.draw do
  get "test/start"

  resources :systems

  resources :rules

  resources :conclusions

  resources :premises

  resources :values

  resources :variables

  root :to => 'test#start'

  
  match 'variables/:variable_id/values' => 'values#variables_values'
  
  match 'test/start/:system_id' => 'test#start_test'
end

app/models/system.rb
class System < ActiveRecord::Base
  attr_accessible :description, :premise_id
  
  has_many :rules
end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  # GET /systems
  # GET /systems.json
  def index
    @systems = System.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @systems }
    end
  end

  # GET /systems/1
  # GET /systems/1.json
  def show
    @system = System.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @system }
    end
  end

  # GET /systems/new
  # GET /systems/new.json
  def new
    @system = System.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @system }
    end
  end

  # GET /systems/1/edit
  def edit
    @system = System.find(params[:id])
  end

  # POST /systems
  # POST /systems.json
  def create
    @system = System.new(params[:system])
    value = Value.find(params[:value][:value_id])
    @system.premise_id = Premise.create!(:variable_id => value.variable.id, :value_id => value.id).id
    respond_to do |format|
      if @system.save
        format.html { redirect_to @system, notice: 'System was successfully created.' }
        format.json { render json: @system, status: :created, location: @system }
      else
        format.html { render action: "new" }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /systems/1
  # PUT /systems/1.json
  def update
    @system = System.find(params[:id])

    respond_to do |format|
      if @system.update_attributes(params[:system])
        format.html { redirect_to @system, notice: 'System was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /systems/1
  # DELETE /systems/1.json
  def destroy
    @system = System.find(params[:id])
    @system.destroy

    respond_to do |format|
      format.html { redirect_to systems_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/systems/_form.html.erb
<%= form_for(@system) do |f| %>
  <% if @system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@system.errors.count, "error") %> prohibited this system from being saved:</h2>

      <ul>
      <% @system.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
 
  <div class="field"> 
    <%= label_tag(:premise, "Premise") %><br />
    <%= grouped_collection_select(:value, :value_id, Variable.all, :values, :description, :id, :description) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/systems/_form_rule.html.erb
<%= form_for(rule) do |f| %>
  <%= f.hidden_field :system_id %>
  <% if rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/systems/_rule_list.html.erb
<h1>Listing rules</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% rules.each do |rule| %>
  <tr>
    <td><%= rule.description %></td>
    <td><%= link_to 'Show', rule %></td>
    <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
    <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/systems/edit.html.erb
<h1>Editing system</h1>

<%= render 'form' %>

<%= link_to 'Show', @system %> |
<%= link_to 'Back', systems_path %>

app/views/systems/index.html.erb
<h1>Listing systems</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Premise</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @systems.each do |system| %>
  <tr>
    <td><%= system.description %></td>
    <td><%= system.premise_id %></td>
    <td><%= link_to 'Show', system %></td>
    <td><%= link_to 'Edit', edit_system_path(system) %></td>
    <td><%= link_to 'Destroy', system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New System', new_system_path %>

app/views/systems/new.html.erb
<h1>New system</h1>

<%= render 'form' %>

<%= link_to 'Back', systems_path %>

app/views/systems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @system.description %>
</p>

<p>
  <b>Premise:</b>
  <%= @system.premise_id %>
</p>

<%= render :partial => "rule_list", :locals => { :rules => @system.rules } %>

<%= render :partial => "form_rule", :locals => { :rule => Rule.new(:system_id => @system.id) } %>


<%= link_to 'Edit', edit_system_path(@system) %> |
<%= link_to 'Back', systems_path %>