config/routes.rb
Projeto02::Application.routes.draw do
  get "test/start"

  resources :systems

  resources :rules

  resources :conclusions

  resources :premises

  resources :values

  resources :variables

  root :to => 'test#start'

  
  match 'variables/:variable_id/values' => 'values#variables_values'
  
  match 'test/start/:system_id' => 'test#start_test'
end

app/models/variable.rb
class Variable < ActiveRecord::Base
  attr_accessible :description
  has_many :values
end

app/controllers/variables_controller.rb
class VariablesController < ApplicationController
  # GET /variables
  # GET /variables.json
  def index
    @variables = Variable.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @variables }
    end
  end

  # GET /variables/1
  # GET /variables/1.json
  def show
    @variable = Variable.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @variable }
    end
  end

  # GET /variables/new
  # GET /variables/new.json
  def new
    @variable = Variable.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @variable }
    end
  end

  # GET /variables/1/edit
  def edit
    @variable = Variable.find(params[:id])
  end

  # POST /variables
  # POST /variables.json
  def create
    @variable = Variable.new(params[:variable])

    respond_to do |format|
      if @variable.save
        format.html { redirect_to @variable, notice: 'Variable was successfully created.' }
        format.json { render json: @variable, status: :created, location: @variable }
      else
        format.html { render action: "new" }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /variables/1
  # PUT /variables/1.json
  def update
    @variable = Variable.find(params[:id])

    respond_to do |format|
      if @variable.update_attributes(params[:variable])
        format.html { redirect_to @variable, notice: 'Variable was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @variable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variables/1
  # DELETE /variables/1.json
  def destroy
    @variable = Variable.find(params[:id])
    @variable.destroy

    respond_to do |format|
      format.html { redirect_to variables_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/variables_helper.rb
module VariablesHelper
end

app/views/variables/_form.html.erb
<%= form_for(@variable) do |f| %>
  <% if @variable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variable.errors.count, "error") %> prohibited this variable from being saved:</h2>

      <ul>
      <% @variable.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variables/_new_value.html.erb
<p>
  <b>New value</b>
</p>

<%= form_for(value) do |f| %>

  <%= f.hidden_field :variable_id %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variables/_value_list.html.erb
<p>
  <b>Listing values</b>
</p>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% values.each do |value| %>
  <tr>
    <td><%= value.description %></td>
    <td><%= link_to 'Show', value %></td>
    <td><%= link_to 'Edit', edit_value_path(value) %></td>
    <td><%= link_to 'Destroy', value, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/variables/edit.html.erb
<h1>Editing variable</h1>

<%= render 'form' %>

<%= link_to 'Show', @variable %> |
<%= link_to 'Back', variables_path %>

app/views/variables/index.html.erb
<h1>Listing variables</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @variables.each do |variable| %>
  <tr>
    <td><%= variable.description %></td>
    <td><%= link_to 'Show', variable %></td>
    <td><%= link_to 'Edit', edit_variable_path(variable) %></td>
    <td><%= link_to 'Destroy', variable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Variable', new_variable_path %>

app/views/variables/new.html.erb
<h1>New variable</h1>

<%= render 'form' %>

<%= link_to 'Back', variables_path %>

app/views/variables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @variable.description %>
</p>

<%= render :partial=> "value_list", :locals=> { :values=> @variable.values } %>

<%= render :partial=> "new_value", :locals=> { :value=> Value.new(:variable_id=> @variable.id) } %>

<%= link_to 'Edit', edit_variable_path(@variable) %> |
<%= link_to 'Back', variables_path %>