config/routes.rb
Projeto02::Application.routes.draw do
  get "test/start"

  resources :systems

  resources :rules

  resources :conclusions

  resources :premises

  resources :values

  resources :variables

  root :to => 'test#start'

  
  match 'variables/:variable_id/values' => 'values#variables_values'
  
  match 'test/start/:system_id' => 'test#start_test'
end

app/models/rule.rb
class Rule < ActiveRecord::Base
  attr_accessible :description, :system_id
  
  has_many :premises
  has_many :conclusions
  
  belongs_to :system
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rules }
    end
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
    @rule = Rule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/new
  # GET /rules/new.json
  def new
    @rule = Rule.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rule }
    end
  end

  # GET /rules/1/edit
  def edit
    @rule = Rule.find(params[:id])
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(params[:rule])
    respond_to do |format|
      if @rule.save
        @premise = Premise.find(@rule.system.premise_id)
        @rule.premises.create(:variable_id => @premise.variable_id, :value_id => @premise.value_id)
        
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render json: @rule, status: :created, location: @rule }
      else
        format.html { render action: "new" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rules/1
  # PUT /rules/1.json
  def update
    @rule = Rule.find(params[:id])

    respond_to do |format|
      if @rule.update_attributes(params[:rule])
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule = Rule.find(params[:id])
    @rule.destroy

    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_conclusion_list.html.erb
<h1>Listing conclusions</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% conclusions.each do |conclusion| %>
  <tr>
    <td><%= conclusion.description %></td>
    <td><%= link_to 'Show', conclusion %></td>
    <td><%= link_to 'Edit', edit_conclusion_path(conclusion) %></td>
    <td><%= link_to 'Destroy', conclusion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/_form_conclusion.html.erb
<%= form_for(conclusion) do |f| %>
  <% if conclusion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@onclusion.errors.count, "error") %> prohibited this conclusion from being saved:</h2>

      <ul>
      <% conclusion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/_form_premise.html.erb
<%= form_for(premise) do |f| %>
  <%= f.hidden_field :rule_id %>

  <% if premise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(premise.errors.count, "error") %> prohibited this premise from being saved:</h2>

      <ul>
      <% premise.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field"> 
  <%= grouped_collection_select(:premise, :value_id, Variable.all, :values, :description, :id, :description) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/_premise_list.html.erb
<h1>Listing premises</h1>

<table>
  <tr>
    <th>Variable</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% premises.each do |premise| %>
  <tr>
    <td><%= Variable.find(premise.variable_id).description %></td>
    <td><%= Value.find(premise.value_id).description %></td>
    <td><%= link_to 'Show', premise %></td>
    <td><%= link_to 'Edit', edit_premise_path(premise) %></td>
    <td><%= link_to 'Destroy', premise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h1>Listing rules</h1>

<table>
  <tr>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rules.each do |rule| %>
  <tr>
    <td><%= rule.description %></td>
    <td><%= link_to 'Show', rule %></td>
    <td><%= link_to 'Edit', edit_rule_path(rule) %></td>
    <td><%= link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Rule', new_rule_path %>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Description:</b>
  <%= @rule.description %>
</p>

<%= render :partial => "premise_list", :locals => { :premises=> @rule.premises } %>

<p>
  <b>Nova Premissa</b>
  <%= render :partial => "form_premise", :locals => { :premise => Premise.new(:rule_id => @rule.id) } %>
</p>

<%= render :partial => "conclusion_list", :locals => { :conclusions => @rule.conclusions } %>

<%= render :partial => "form_conclusion", :locals => { :conclusion => Conclusion.new(:rule_id => @rule.id) }%>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>